version: '3'

services:
  web:
    container_name: app
    build: .
    ports:
      - "5000:5000"
    networks:
      - identinet
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    expose:
      - "9200:9200"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - identinet


networks:
  identinet:
    driver: bridge